[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ndsl"
version = "2025.05.00"
dynamic = ["dependencies"]
requires-python = ">=3.11,<3.12"
authors = [{name = "NOAA/NASA"}]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE.txt", "ndsl/viz/fv3/README.md"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Private :: Do Not Upload",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]

[project.optional-dependencies]
docs = ["mkdocs-material"]
demos = ["ipython", "ipykernel"]
test = ["pytest", "pytest-subtests", "coverage"]
develop = [
    "ndsl[docs]",
    "ndsl[demos]",
    "ndsl[test]",
    "pre-commit",
    "pyproject-flake8"
]
extras = [
    "ndsl[docs]",
    "ndsl[demos]",
    "ndsl[test]",
    "ndsl[develop]",
]

[project.scripts]
ndsl-serialbox_to_netcdf = "ndsl.stencils.testing.serialbox_to_netcdf:entry_point"

[project.urls]
Repository = "https://github.com/NOAA-GFDL/NDSL"

[tool.setuptools.packages.find]
include = ["ndsl", "ndsl.*"]

[tool.setuptools]
include-package-data = true

[tool.flake8]
exclude = ["docs"]
extend-ignore = ["E203","E302","E704","F841","W293","E501","W503"]
max-line-length = 88

[tool.isort]
profile = "black"
lines_after_imports = 2
default_section = "THIRDPARTY"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
known_third_party = "f90nml,pytest,xarray,numpy,mpi4py,gt4py,dace"

[tool.mypy]
ignore_missing_imports = "true"
follow_imports = "normal"
namespace_packages = "true"
strict_optional = "false"
warn_unreachable = "true"
explicit_package_bases = "true"

[tool.coverage.run]
parallel = true
branch = true
omit = ["tests/*", "*gt_cache*", ".dacecache*", "external/*", "__init__.py"]
source_pkgs = "ndsl"
