# This file tests `ndsl-gencode`, the code generator that's shipped with NDSL.
name: "NDSL codgen tests"

# Run these these whenever ...
on:
  pull_request: # ... a PR is opened / updated
  merge_group: # ... the PR is added to the merge queue
  push:
    branches:
      - main # ... when merging into the main branch

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ndsl_gencode_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
      fail-fast: true
    name: ndsl-gencode (py${{ matrix.python-version }})
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Generate and run code
        run: |
          uv init test
          cd test/
          # github.sha contains the merge commit of this PR with the base branch
          uv add git+https://github.com/noaa-gfdl/ndsl.git --extra openmpi --rev ${{ github.sha }}
          source .venv/bin/activate
          python --version
          ndsl-gencode --exec --output test_ndsl_gencode.py
          python test_ndsl_gencode.py
