name: "NDSL docs deploy"

# Documentation gets automatically deployed upon merge to develop
on:
  push:
    branches:
      - develop

# Security: Restrict permissions of this workflow to whats needed.
permissions:
  contents: read
  pages: write
  id-token: write

env:
  UV_FROZEN: 1 # sync without updating uv.lock
  UV_NO_DEV: 1 # don't install dev dependency group by default
  UV_NO_EDITABLE: 1 # don't install NDSL in editable mode

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - run: uv run -only-group=docs zensical build
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - uses: actions/deploy-pages@v5
        id: deployment
