name: "NDSL unit tests"

# Run these these whenever ...
on:
  pull_request: # ... a PR is opened / updated
  merge_group: # ... the PR is added to the merge queue
  push:
    branches:
      - main # ... when merging into the main branch

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ndsl_unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
        extra: ['openmpi,zarr']
        marker-serial: ['not parallel and not gpu and not pyfms']
        marker-parallel: ['parallel and not gpu and not pyfms']
        include:
          # add pyfms tests for 3.12
          - extra: 'pyfms'
            marker-serial: 'pyfms and not parallel'
            marker-parallel: 'pyfms and parallel'
            python-version: '3.12'
      # don't cancel other jobs if one fails
      fail-fast: false
    name: Python ${{ matrix.python-version }}${{ contains(matrix.extra, 'pyfms') && ' (pyFMS)' || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install pyFMS dependencies (includes system MPI)
        if: contains(matrix.extra, 'pyfms')
        run: |
          sudo apt-get update
          sudo apt-get install libopenmpi-dev netcdf-bin libnetcdf-dev libnetcdff-dev nco libyaml-dev diffutils

      - name: Install Python packages
        run: uv sync --group test --extra ${{matrix.extra}} --no-dev

      - name: Run serial cpu tests
        run: uv run coverage run --rcfile=pyproject.toml -m pytest -m "${{matrix.marker-serial}}" tests

      - name: Run parallel cpu tests
        run: uv run mpiexec -np 6 --oversubscribe coverage run --rcfile=pyproject.toml -m mpi4py -m pytest -m "${{matrix.marker-parallel}}" tests

      - name: Output code coverage
        run: |
          uv run coverage combine
          uv run coverage report
